server:
  port: 9000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000